#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/.local/share/ ~/Projects -maxdepth 2 -type d -name .git | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_path=$(dirname "$selected")
selected_name=$(basename "$selected_path" | tr . _)
tmux_running=$(pgrep tmux)

if ! byobu has-session -t=$selected_name 2> /dev/null; then
    byobu new-session -ds $selected_name -c $selected_path nvim .
fi

if [[ -z $BYOBU ]] && [[ -z $tmux_running ]]; then
    byobu new-session -s $selected_name -c $selected_path nvim .
    exit 0
fi

byobu switch-client -t $selected_name

