[pyprland]
plugins = ["toggle_special", "magnify", "shift_monitors", "system_notifier", "scratchpads"]

[scratchpads.spotify]
animation = "fromTop"
command = "spotify"
class = "Spotify"
size = "100% 100%"
max_size = "1920px 100%"
margin = 50

